version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - pip install -U pytest
  build:
    commands:
      - echo Build started on `date`
      - pytest test/$DEPLOY_LAMBDA_NAME/test.py
  post_build:
    commands:
      - echo Build completed on `date`
      - bash scripts/deploy.sh 
artifacts:
  files:
    - 'dist/*'
  name: codeDeploy/$DEPLOY_LAMBDA_NAME/source.zip