version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - ehco Build started
      - python main.py
  post_build:
    commands:
      - ehco Build completed
artifacts:
  files:
    - '**/*'
  name: artifact-$(date +%Y-%m-%d)